package Example;

import org.w3c.dom.ls.LSInput;

import java.util.Scanner;

public class Cars {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        System.out.print ("How many car you have: ");
        int n = input.nextInt();
        car [] sport_car = new car[n];


        for(int i =0;i < n;i++){
            System.out.println("Enter the Information of Car "+(i+1));
            input.nextLine();
            System.out.print("Enter the name of car: ");
            String name = input.nextLine();
            input.nextLine();
            System.out.print("Which engine has: " );
            String engine = input.nextLine();
            input.nextLine();
            System.out.print("Power generated by: ");
            String power = input.nextLine();
            input.nextLine();
            System.out.print("how much torque does in engine: ");
            String torque = input.nextLine();
            input.nextLine();
            System.out.print("Top speed of: ");
            String top_speed = input.nextLine();
            sport_car[i] = new car(name,torque,engine,power,top_speed);
            System.out.println("----------------------------------------------------------------------------------------------------");
        }

        for(int i = 0;i < n;i++){
            System.out.println("Information for Car "+(i+1));
            sport_car[i].display();
            System.out.println("----------------------------------------------------------------------------------------------------");
            System.out.println();
        }

    }

}
class car {
    String name;
    String torque;
    String engine;
    String max_power;
    String top_speed;

    car  (String name,String torque,String engine,String max_power,String top_speed) {
        this.name = name;
        this.engine =engine;
        this.torque = torque;
        this.max_power  =max_power;
        this.top_speed = top_speed;
    }
    void display(){
        System.out.println("Name of car is: " + this.name );
        System.out.println("Engine of "+this.name+ " is " + this.engine);
        System.out.println("Maximum power generated by " + this.name + " is " + this.max_power);
        System.out.println("Torque of "+this.name+" is: "+this.torque);
        System.out.println("Top speed of "+this.name+" is: " + this.top_speed );
    }
}
/*
    Output:

    How many car you have: 2
Enter the Information of Car 1
Enter the name of car: BMW M5cs
Which engine has: 4395 cc,V8 Engine
Power generated by: 617 BHp
how much torque does in engine: 750 Nm
Top speed of: 333 Km/h
----------------------------------------------------------------------------------------------------
Enter the Information of Car 2

Enter the name of car: Aston Martine DBS 770 Ultimate
Which engine has: 5.2 Litre, V12 Engine
Power generated by: 770 Ps
how much torque does in engine: 900Nm
Top speed of: 340 Km/h
----------------------------------------------------------------------------------------------------
Information for Car 1
Name of car is: BMW M5cs
Engine of BMW M5cs is 4395 cc,V8 Engine
Maximum power generated by BMW M5cs is 617 Bhp
Torque of BMW M5cs is: 750 Nm
Top speed of BMW M5cs is: 333 Km/h
----------------------------------------------------------------------------------------------------

Information for Car 2
Name of car is: Aston Martine DBS 770 Ultimate
Engine of Aston Martine DBS 770 Ultimate  is 5.2 Litre, V12 Engine
Maximum power generated by Aston Martine DBS 770 Ultimate  is 770 Ps
Torque of Aston Martine DBS 770 Ultimate  is: 900Nm
Top speed of Aston Martine DBS 770 Ultimate  is: 340 Km/h
----------------------------------------------------------------------------------------------------



*/